name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: nikiakbar
        password: ${{ secrets.$DOCKERHUB_PAT }} 
    - name: Build the Docker image
      run: docker build . --tag nikiakbar/runpod-automatic1111:latest
    - name: Push the Docker image
      run: docker push nikiakbar/runpod-automatic1111:latest


